name: Development Workflow

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Fix permissions for htmlhint
        run: chmod +x ./node_modules/.bin/htmlhint

      - name: Run HTMLHint
        run: npm run lint:html

      - name: Run Stylelint
        run: npm run lint:css

      - name: Build Project with Parcel
        run: npx parcel build src/*.html --dist-dir build --public-url /term-project/

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/develop'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages-dev